services:
  web:
    container_name: tawBack
    restart: always
    build: .
    ports:
         - "5000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'test_database'
      MYSQL_USER: 'suscribete'
      MYSQL_PASSWORD: 'Recuerda_Suscribirte'
      MYSQL_ROOT_PASSWORD: 'D_aleLike'
      MYSQL_ROOT_PASSWORD: 'D_aleLike'
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3307
    ports:
      - 3307:3306
    platform: linux/x86_64
